language: python

python:
  - 2.7
  - 3.4

env:
  - DJANGOVER=django18
  - DJANGOVER=django19
  - TOX_ENV=demo
  - TOX_ENV=docs

install:
  - pip install tox

script:
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' && $DJANGOVER ]]; then export TOX_ENV=py27-$DJANGOVER; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.4' && $DJANGOVER ]]; then export TOX_ENV=py34-$DJANGOVER; fi"
  - tox -r -e "$TOX_ENV"

matrix:
  allow_failures:
    - env: DJANGOVER=django19
    - python: 3.4
  exclude:
    - python: 3.4
      env: TOX_ENV=demo
    - python: 3.4
      env: TOX_ENV=docs
