language: python
python:
  - "2.7"
env:
  - TOX_ENV=py27-django18
  - TOX_ENV=py27-django19
  - TOX_ENV=demo
install:
  - pip install tox
script:
  - tox -r -e $TOX_ENV
matrix:
  allow_failures:
    - env: TOX_ENV=py27-django19
