language: python

python:
  - 2.7
  - 3.5

env:
  - DJANGOVER=django19
  - DJANGOVER=django110
  - TOX_ENV=docs

install:
  - pip install tox

script:
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' && $DJANGOVER ]]; then export TOX_ENV=py27-$DJANGOVER; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.5' && $DJANGOVER ]]; then export TOX_ENV=py35-$DJANGOVER; fi"
  - tox -r -e "$TOX_ENV"
